# conda env create -f environment.yml
name: lume-belt-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - eval-type-backport
  - lume-base
  - numpy
  - prettytable
  - psutil
  - pydantic >2
  - pydantic-settings
  # Developer
  - ffmpeg
  - pytest
  - pytest-cov
  - jupyterlab>=3
  - jupyterlab-lsp
  - python-lsp-server
  - matplotlib
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  # NOTE: we are installing mkdocs-jupyter with pip for now
  # due to the following: https://github.com/conda-forge/mkdocs-jupyter-feedstock/issues/31
  # - mkdocs-jupyter
  - mkdocstrings-python
  - ruff
  - typing-extensions
  - pip:
      # Install this package as well
      - .
      - mkdocs-jupyter>=0.24.7
